name: Godot Android export
on: push
jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
      - uses: dulvui/godot-android-export@v4.0.0
        with:
          working-directory: ./
          godot-version: 4.2
