name: Godot Android export
on: push
jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
      - uses: dulvui/godot-android-export@v4.0.0
        with:
          working-directory: ./
          godot-version: 4.2
      - name: Bundle aab to apk
        run: |
          wget -q https://github.com/google/bundletool/releases/download/1.14.0/bundletool-all-1.14.0.jar
          java -jar bundletool-all-1.14.0.jar build-apks --bundle=FutsalManager.aab --output=FutsalManager.apks \
          --mode=universal
          unzip -p FutsalManager.apks universal.apk > FutsalManager.apk
